### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by Singulariity** [Singulariity/satorugojo-isaac#1]
# Tasks to do

Tasks that need to be completed for the first release of the mod. (for now)

## Characters
* Gojo
  - [x] [players.xml](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/content/players.xml)
  - [x] [controls.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/content/gfx/controls.png)
  - [x] [coop_icon.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/content/gfx/coop_icon.png)
  - [x] [deathname_gojo.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/content/gfx/deathname_gojo.png)
  - [x] [menu gojo.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/content/gfx/menu%20gojo.png)
  - [x] [**all the costumes**](https://github.com/Singulariity/satorugojo-isaac/tree/master/src/resources/gfx/characters/costumes)
  - [x] [gojo hair.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/characters/costumes/gojo%20hair.png)
  - [x] [playername_gojo.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/ui/boss/playername_gojo.png)
  - [x] [playerportrait_gojo.png](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/ui/stage/playerportrait_gojo.png)

## Items
* Infinite Void
  - [x] [Icon](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/items/collectibles/infinite_void.png)
  - [ ] [Achievement](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/ui/achievements/achievement_infinite_void.png)
  - [ ] [Giantbook Animation Image](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/ui/giantbook/infinite_void.png)
* Limit
  - [x] [Icon](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/items/collectibles/limit.png)
  - [ ] [Achievement](https://github.com/Singulariity/satorugojo-isaac/blob/master/src/resources/gfx/ui/achievements/achievement_limit.png)
